put http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "_id": 
  "mensaje": "Me quieren demandar por pensión de alimentos"
  "usuarioId": "6719813cf7916b8c12deaa41"
  "abogadoId": ""
  "estado": "no asignado"
  "fecha_creacion": "25-10-2024"
}